-- Deprecated no-op.
-- Run after 020_refund_expense_entries.sql.
--
-- Customer refunds are revenue corrections, not shop expenses. This migration
-- used to backfill Stripe customer refunds into expense_entries and is left
-- intentionally empty so fresh databases do not import them as costs.
